export const titleMap = {
'accountsPayable': 'Accounts Payable',
'currentAssets': 'Current Assets',
'currentCash': 'Cash & Equivalents',
'currentLongTermDebt': 'Current Long-Term Debt',
'goodwill': 'Goodwill',
'intangibleAssets': 'Intangible Assets',
'inventory': 'Inventory',
'longTermDebt': 'Long-Term Debt',
'longTermInvestments': 'Long-Term Investments',
'minorityInterest': 'Minority Interest',
'netTangibleAssets': 'Net Tangible Assets',
'otherAssets': 'Other Assets',
'otherCurrentAssets': 'Other Current Assets',
'otherCurrentLiabilities': 'Other Current Liabilities',
'otherLiabilities': 'Other Liabilities',
'propertyPlantEquipment': 'Property & Equipment',
'receivables': 'Accounts Receivable',
'retainedEarnings': 'Retained Earnings',
'shareholderEquity': 'Shareholder Equity',
'shortTermInvestments': 'Short-Term Investments',
'totalAssets': 'Total Assets',
'totalCurrentLiabilities': 'Total Current Liabilities',
'totalLiabilities': 'Total Liabilities',
'capitalExpenditures': 'Capex',
'cashChange': 'Cash Change',
'cashFlow': 'Cash Flow',
'cashFlowFinancing': 'Financing Cash Flow',
'changesInInventories': 'Inv. Changes',
'changesInReceivables': 'Rec. Changes',
'depreciation': 'Depreciation',
'dividendsPaid': 'Dividends Paid',
'exchangeRateEffect': 'FX Rate Effect',
'investingActivityOther': 'Other Inv. Activities',
'investments': 'Investments',
'netBorrowings': 'Net Borrowings',
'netIncome': 'Net Income',
'otherFinancingCashFlows': 'Other Financing Cash Flows',
'totalInvestingCashFlows': 'Total Inv. Cash Flow',
'costOfRevenue': 'Cost of Revenue',
'ebit': 'EBIT',
'grossProfit': 'Gross Profit',
'incomeTax': 'Income Tax',
'interestIncome': 'Interest Income',
'minorityInterest': 'Minority Interest',
'netIncomeBasic': 'Net Income (Basic)',
'operatingExpense': 'Opex',
'operatingIncome': 'Operating Income',
'otherIncomeExpenseNet': 'Other Income, Net',
'pretaxIncome': 'Pretax Income',
'researchAndDevelopment': 'R&D',
'sellingGeneralAndAdmin': 'Selling & Admin',
'totalRevenue': 'Total Revenue',
'capitalSurplus': 'Capital Surplus',
'commonStock': 'Common Stock',
'treasuryStock': 'treasury Stock'
};

export const CompactSummaryKeys = [
	'EBITDA',
	'debtToEquity',
	'forwardPERatio',
	'enterpriseValueToRevenue',
	'priceToBook',
	'priceToSales',
	'profitMargin',
	'putCallRatio',
	'ytdChangePercent'
	];

export const SummaryKeyMap = {
  nextEarningsDate: 'Next Earnings',
  dividendYield: 'Div. Yield',
  marketcap: 'Mkt Cap',
  beta: 'Beta',
  avg30Volume: '30d Volume',
  EBITDA: 'EBITDA',
  debtToEquity: 'Debt/Equity',
  forwardPERatio: 'Forward P/E',
  enterpriseValueToRevenue: 'EV/Rev',
  priceToBook: 'P/B',
  priceToSales: 'P/S',
  profitMargin: 'Profit Margin',
  putCallRatio: 'Put/Call Ratio',
  ytdChangePercent: 'YTD Change'
	};